"""empty message

Revision ID: b4b140b4e2d9
Revises: 
Create Date: 2021-10-24 22:19:57.923403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4b140b4e2d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('nim', sa.Integer(), nullable=True),
    sa.Column('visi', sa.Text(), nullable=True),
    sa.Column('misi', sa.Text(), nullable=True),
    sa.Column('display', sa.Boolean(), nullable=True),
    sa.Column('counts', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nim')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nim', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('voted', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('selfi', sa.String(), nullable=True),
    sa.Column('birthday', sa.String(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('vote_is_canceled', sa.Boolean(), nullable=True),
    sa.Column('is_allowed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nim')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('candidate')
    # ### end Alembic commands ###
